default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    upload_to_play_store(track: 'production')
  end
end

default_platform(:ios)

platform :ios do
  desc "Deploy a new version to the App Store"
  lane :deploy do
    build_app(scheme: "YourAppScheme")
    upload_to_app_store
  end
end 